Traceback (most recent call last):
  File "neural_main.py", line 54, in <module>
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "/project2/nicho/weiliang/videoNet/code/train.py", line 64, in train
    lfp_start_ms,lfp_end_ms,vel_start_ms,vel_end_ms,lfp_ms_for_vel,)
  File "/project2/nicho/weiliang/videoNet/code/video_supportive.py", line 163, in readAndDivideData
    lfp_matrix_final,vel_final,train_ratio,val_ratio,test_ratio,seed)
  File "/project2/nicho/weiliang/videoNet/code/video_supportive.py", line 174, in divideXyIntoThreeSets
    test_size=1-train_ratio, shuffle=True,random_state=seed)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/tf-gpu-2.1-cuda-10.1/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 2118, in train_test_split
    arrays = indexable(*arrays)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/tf-gpu-2.1-cuda-10.1/lib/python3.7/site-packages/sklearn/utils/validation.py", line 248, in indexable
    check_consistent_length(*result)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/tf-gpu-2.1-cuda-10.1/lib/python3.7/site-packages/sklearn/utils/validation.py", line 212, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [39360, 2]
